// cli/inventory.mjs
// Inventory state: which components are installed vs available.
// Lives at <consumer-root>/klp-inventory.json; maintained by klep-ds-init + klp-ui add.

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const FILE = 'klp-inventory.json'
const SCHEMA = 'v1'

export function createInventory({ ref, brand, appDir, dsDir, catalog, initiallyInstalled = [] }) {
  const installed = new Set(initiallyInstalled)
  const components = {}
  for (const e of catalog) {
    components[e.name] = {
      status: installed.has(e.name) ? 'installed' : 'available',
      category: e.category,
      deps: e.deps ?? [],
    }
  }
  return { schemaVersion: SCHEMA, ref, brand, appDir, dsDir, components }
}

export function inventoryPath(rootDir) { return join(rootDir, FILE) }
export function readInventory(rootDir) { return JSON.parse(readFileSync(inventoryPath(rootDir), 'utf8')) }
export function writeInventory(rootDir, inv) {
  writeFileSync(inventoryPath(rootDir), JSON.stringify(inv, null, 2) + '\n')
}

export function markInstalled(inv, names) {
  const next = JSON.parse(JSON.stringify(inv))
  for (const name of names) if (next.components[name]) next.components[name].status = 'installed'
  return next
}

export function listByStatus(inv, status) {
  return Object.entries(inv.components).filter(([, v]) => v.status === status).map(([k]) => k)
}

export function writeInventoryMd(rootDir, inventory) {
  const byStatus = { installed: [], available: [] }
  for (const [name, c] of Object.entries(inventory.components)) {
    byStatus[c.status]?.push({ name, ...c })
  }
  const groupByCategory = (arr) => {
    const out = {}
    for (const e of arr) (out[e.category] ??= []).push(e)
    for (const k of Object.keys(out)) out[k].sort((a, b) => a.name.localeCompare(b.name))
    return out
  }
  const installedByCat = groupByCategory(byStatus.installed)
  const availableByCat = groupByCategory(byStatus.available)
  const now = new Date().toISOString().slice(0, 10)

  const lines = []
  lines.push(`# klp-ui inventory`)
  lines.push('')
  lines.push(`> Auto-generated by \`klep-ds-init\` and \`klp-ui add\`. **Do not edit by hand** — your changes will be overwritten on next install.`)
  lines.push('')
  lines.push(`- **Brand:** \`${inventory.brand}\``)
  lines.push(`- **Ref:** \`${inventory.ref}\``)
  lines.push(`- **Generated:** ${now}`)
  lines.push(`- **Installed:** ${byStatus.installed.length} / ${byStatus.installed.length + byStatus.available.length}`)
  lines.push('')

  lines.push(`## Installed`)
  lines.push('')
  if (byStatus.installed.length === 0) {
    lines.push('_None yet. Run `klp-ui add <name>` to install a component._')
    lines.push('')
  } else {
    for (const [cat, items] of Object.entries(installedByCat).sort()) {
      lines.push(`### ${cat}`)
      lines.push('')
      for (const c of items) {
        const docLink = `[docs](./docs/components/_index_${c.name}.md)`
        const depsTag = c.deps.length ? ` _(deps: ${c.deps.join(', ')})_` : ''
        lines.push(`- \`${c.name}\` — ${docLink}${depsTag}`)
      }
      lines.push('')
    }
  }

  lines.push(`## Available (not installed)`)
  lines.push('')
  if (byStatus.available.length === 0) {
    lines.push('_All components installed._')
    lines.push('')
  } else {
    lines.push(`Add via \`klp-ui add <name>\`. Transitive deps auto-resolved.`)
    lines.push('')
    for (const [cat, items] of Object.entries(availableByCat).sort()) {
      lines.push(`### ${cat}`)
      lines.push('')
      for (const c of items) {
        const depsTag = c.deps.length ? ` _(pulls: ${c.deps.join(', ')})_` : ''
        lines.push(`- \`${c.name}\`${depsTag}`)
      }
      lines.push('')
    }
  }

  writeFileSync(join(rootDir, 'klp-inventory.md'), lines.join('\n'))
}

export function resolveTransitive(inv, names) {
  const out = new Set(names)
  let changed = true
  while (changed) {
    changed = false
    for (const n of Array.from(out)) {
      const e = inv.components[n]
      if (!e) continue
      for (const d of e.deps) if (!out.has(d)) { out.add(d); changed = true }
    }
  }
  return Array.from(out)
}
