#!/usr/bin/env tsx
/**
 * sync-tokens — regenerate CSS layers from .klp/tokens.json.
 *
 * Input:  .klp/tokens.json  (source of truth, refreshed via Figma Console MCP)
 * Output: src/styles/tokens/primitives.css
 *         src/styles/tokens/aliases.css
 *         src/styles/tokens/theme.css
 *
 * The script is idempotent: two successive runs produce identical files.
 * tokens.css (orchestrator) is NOT rewritten — it only @imports the three
 * layers and holds the preserved `--- manual additions ---` section.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

// ────────────────────────────────────────────────────────────────────────────
// Types

type Brand = 'wireframe' | 'klub' | 'atlas' | 'showup'

interface TokensFile {
  fileKey: string
  fileName: string
  capturedAt: string
  brands: Brand[]
  defaultBrand: Brand
  fallbacks: { spacing: Partial<Record<Brand, Brand>>; font: Partial<Record<Brand, Brand>> }
  primitives: {
    colors: Record<string, string>
    spacings: Record<string, string>
    radii: Record<string, string>
  }
  aliasColors:  Record<string, Partial<Record<Brand, string>>>
  aliasSpacing: Record<string, Partial<Record<Brand, string>>>
  aliasFont:    Record<string, Partial<Record<Brand, string>>>
}

// ────────────────────────────────────────────────────────────────────────────
// Paths

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot  = resolve(__dirname, '..')
const tokensJson = resolve(repoRoot, '.klp/tokens.json')
const outDir     = resolve(repoRoot, 'src/styles/tokens')

// ────────────────────────────────────────────────────────────────────────────
// Helpers

/** Resolve a brand's value for an alias, applying fallback policy. */
function resolveBrand<T>(
  byMode: Partial<Record<Brand, T>>,
  brand: Brand,
  fallbacks: Partial<Record<Brand, Brand>> = {},
): T | undefined {
  if (byMode[brand] !== undefined) return byMode[brand]
  const fb = fallbacks[brand]
  if (fb && byMode[fb] !== undefined) return byMode[fb]
  return undefined
}

function header(title: string, subtitle: string): string {
  return [
    '/* =============================================================================',
    ` * ${title}`,
    ' *',
    ` * ${subtitle}`,
    ' *',
    ' * Auto-generated by `pnpm sync:tokens` — do not edit by hand.',
    ` * Source: .klp/tokens.json (captured ${new Date().toISOString().slice(0, 10)})`,
    ' * =============================================================================*/',
    '',
  ].join('\n')
}

// ────────────────────────────────────────────────────────────────────────────
// Generators

function buildPrimitives(tokens: TokensFile): string {
  const { colors, spacings, radii } = tokens.primitives
  const lines: string[] = []

  lines.push(header(
    '@klp/ui — Layer 1: Primitives',
    'Raw palette + scale values. Not exposed as Tailwind utilities; referenced by alias layer.',
  ))
  lines.push(':root {')
  lines.push('  /* --- colors --- */')
  for (const [name, hex] of Object.entries(colors)) {
    lines.push(`  --klp-color-${name}: ${hex};`)
  }
  lines.push('')
  lines.push('  /* --- spacing scale --- */')
  for (const [name, value] of Object.entries(spacings)) {
    lines.push(`  --klp-spacing-${name}: ${value};`)
  }
  lines.push('')
  lines.push('  /* --- border radius scale --- */')
  for (const [name, value] of Object.entries(radii)) {
    lines.push(`  --klp-radius-${name}: ${value};`)
  }
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

function buildAliases(tokens: TokensFile): string {
  const { brands, defaultBrand, fallbacks } = tokens
  const lines: string[] = []

  lines.push(header(
    '@klp/ui — Layer 2: Aliases',
    `Semantic tokens switched by [data-brand]. Default brand: ${defaultBrand}.`,
  ))

  const emitBlock = (selector: string, brand: Brand) => {
    lines.push(`${selector} {`)

    lines.push('  /* colors */')
    for (const [aliasName, byMode] of Object.entries(tokens.aliasColors)) {
      const primName = resolveBrand(byMode, brand)
      if (!primName) {
        console.warn(`[sync-tokens] ⚠ missing color alias '${aliasName}' for brand '${brand}' — skipped`)
        continue
      }
      lines.push(`  --klp-${aliasName}: var(--klp-color-${primName});`)
    }

    lines.push('')
    lines.push('  /* spacing */')
    for (const [aliasName, byMode] of Object.entries(tokens.aliasSpacing)) {
      const primName = resolveBrand(byMode, brand, fallbacks.spacing)
      if (!primName) {
        console.warn(`[sync-tokens] ⚠ missing spacing alias '${aliasName}' for brand '${brand}' — skipped`)
        continue
      }
      // primName references either a spacing or a radius primitive
      const primRef = primName.startsWith('radius-')
        ? `var(--klp-${primName})`
        : `var(--klp-${primName})`
      lines.push(`  --klp-${aliasName}: ${primRef};`)
    }

    lines.push('')
    lines.push('  /* typography */')
    for (const [aliasName, byMode] of Object.entries(tokens.aliasFont)) {
      const rawValue = resolveBrand(byMode, brand, fallbacks.font)
      if (rawValue === undefined) {
        console.warn(`[sync-tokens] ⚠ missing font alias '${aliasName}' for brand '${brand}' — skipped`)
        continue
      }
      const cssValue = aliasName.startsWith('family-') ? `'${rawValue}', system-ui, sans-serif` : rawValue
      lines.push(`  --klp-font-${aliasName}: ${cssValue};`)
    }

    lines.push('}')
    lines.push('')
  }

  // default = :root (also picks up [data-brand="wireframe"])
  emitBlock(`:root,\n[data-brand="${defaultBrand}"]`, defaultBrand)
  for (const brand of brands) {
    if (brand === defaultBrand) continue
    emitBlock(`[data-brand="${brand}"]`, brand)
  }

  return lines.join('\n')
}

function buildTheme(tokens: TokensFile): string {
  const lines: string[] = []
  lines.push(header(
    '@klp/ui — Layer 3: Tailwind theme',
    'Maps semantic aliases to Tailwind v4 utility namespaces (klp-*). @theme inline is required for runtime brand switching.',
  ))

  lines.push('@theme inline {')

  lines.push('  /* colors → bg-klp-*, text-klp-*, border-klp-*, etc. */')
  for (const aliasName of Object.keys(tokens.aliasColors)) {
    lines.push(`  --color-klp-${aliasName}: var(--klp-${aliasName});`)
  }

  lines.push('')
  lines.push('  /* spacing → p-klp-*, m-klp-*, gap-klp-*, w-klp-*, h-klp-* */')
  for (const aliasName of Object.keys(tokens.aliasSpacing)) {
    if (aliasName.startsWith('radius-')) continue   // handled below
    lines.push(`  --spacing-klp-${aliasName}: var(--klp-${aliasName});`)
  }

  lines.push('')
  lines.push('  /* radius → rounded-klp-* */')
  for (const aliasName of Object.keys(tokens.aliasSpacing)) {
    if (!aliasName.startsWith('radius-')) continue
    // strip "radius-" prefix for Tailwind utility name (rounded-klp-m not rounded-klp-radius-m)
    const util = aliasName.replace(/^radius-/, '')
    lines.push(`  --radius-klp-${util}: var(--klp-${aliasName});`)
  }

  lines.push('')
  lines.push('  /* typography — font family, font weight, text size */')
  for (const aliasName of Object.keys(tokens.aliasFont)) {
    if (aliasName.startsWith('family-')) {
      // family-title → font-klp-title
      const util = aliasName.replace(/^family-/, '')
      lines.push(`  --font-klp-${util}: var(--klp-font-${aliasName});`)
    } else if (aliasName.startsWith('weight-')) {
      const util = aliasName.replace(/^weight-/, '')
      lines.push(`  --font-weight-klp-${util}: var(--klp-font-${aliasName});`)
    } else if (aliasName.startsWith('size-text-') || aliasName.startsWith('size-heading-')) {
      // size-text-large → text-klp-text-large ; size-heading-h1 → text-klp-heading-h1
      const util = aliasName.replace(/^size-/, '')
      lines.push(`  --text-klp-${util}: var(--klp-font-${aliasName});`)
    }
  }

  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

// Tailwind v4 namespace -> the utility prefixes it generates. Keys are the
// namespaces emitted by buildTheme(); see src/styles/tokens/theme.css.
const NAMESPACE_UTILS: Record<string, { label: string; prefixes: string[] }> = {
  color: { label: 'Colors', prefixes: ['bg-', 'text-', 'border-'] },
  spacing: { label: 'Sizing', prefixes: ['p-', 'm-', 'gap-', 'w-', 'h-'] },
  radius: { label: 'Radius', prefixes: ['rounded-'] },
  font: { label: 'Font family', prefixes: ['font-'] },
  'font-weight': { label: 'Font weight', prefixes: ['font-'] },
  text: { label: 'Text size', prefixes: ['text-'] },
}

// Figma collection per alias prefix. The Figma path is <collection>/<leaf>.
function figmaPath(alias: string): string {
  const map: [RegExp, string, boolean][] = [
    [/^bg-/, 'bg', false],
    [/^fg-/, 'fg', false],
    [/^border-/, 'border', false],
    [/^alpha-/, 'alpha', false],
    [/^size-/, 'Sizing', true],
    // default-text lives in aliasSpacing alongside size-*/radius-* — it has no
    // dedicated Figma collection of its own, so it groups under Sizing too.
    [/^default-/, 'Sizing', false],
    [/^radius-/, 'Radius', true],
    [/^font-family-/, 'Font/family', false],
    [/^font-weight-/, 'Font/weight', false],
    [/^font-size-/, 'Font/size', false],
  ]
  for (const [re, collection, upper] of map) {
    if (!re.test(alias)) continue
    const leaf = alias.replace(re, '')
    return `${collection}/${upper ? leaf.toUpperCase() : leaf}`
  }
  // No known collection matched — the generic fallback below invents a
  // section name from the raw alias. That's a guess, not a fact: surface it
  // loudly so the next unmapped alias gets a real case instead of silently
  // fabricating a Figma collection that doesn't exist.
  console.warn(
    `[sync-tokens] ⚠ alias '${alias}' matched no known Figma collection in figmaPath() — falling back to a generic (possibly wrong) path; add a case for it`
  )
  return alias.replace(/-/g, '/')
}

function buildVocabulary(themeCss: string): string {
  const rows: { group: string; figma: string; cssVar: string; utils: string[] }[] = []
  const re = /^\s*--([a-z-]+?)-klp-([a-z0-9-]+):\s*var\(--klp-([a-z0-9-]+)\);/gm
  let m: RegExpExecArray | null
  while ((m = re.exec(themeCss))) {
    const [, namespace, leaf, alias] = m
    const ns = NAMESPACE_UTILS[namespace]
    if (!ns) {
      console.warn(`[sync-tokens] ⚠ unknown theme namespace '${namespace}' — skipped in vocabulary`)
      continue
    }
    const figma = figmaPath(alias)
    rows.push({
      // Group by Figma collection root (bg / fg / border / Sizing / Radius / Font),
      // which is the axis a designer or an agent actually searches by.
      group: figma.split('/')[0],
      figma,
      cssVar: `--klp-${alias}`,
      utils: ns.prefixes.map((p) => `${p}klp-${leaf}`),
    })
  }

  // Tailwind v4 compiles multiple theme namespaces (e.g. --font-* and
  // --font-weight-*) to the same class prefix. When two different CSS
  // variables produce the identical utility string, that utility is
  // ambiguous: only one of the two meanings actually wins in the generated
  // CSS. Detect it here instead of documenting both as if they were both
  // safe to use.
  const utilOwners = new Map<string, Set<string>>()
  for (const r of rows) {
    for (const u of r.utils) {
      if (!utilOwners.has(u)) utilOwners.set(u, new Set())
      utilOwners.get(u)!.add(r.cssVar)
    }
  }
  const collisions = new Map<string, Set<string>>()
  for (const [u, owners] of utilOwners) {
    if (owners.size > 1) collisions.set(u, owners)
  }
  for (const [u, owners] of [...collisions].sort(([a], [b]) => a.localeCompare(b))) {
    console.warn(
      `[sync-tokens] ⚠ utility '${u}' is produced by multiple CSS variables (${[...owners].sort().join(', ')}) — the class is ambiguous, do not rely on it`
    )
  }

  const lines: string[] = []
  lines.push('---')
  lines.push('title: klp-ui — token vocabulary')
  lines.push('type: token-reference')
  lines.push('---')
  lines.push('')
  lines.push('# Token vocabulary')
  lines.push('')
  lines.push('Generated by `pnpm run sync:tokens`. Do not edit by hand.')
  lines.push('')
  lines.push('The mapping is mechanical: lowercase the Figma path, replace `/` with `-`, prefix `--klp-`. Use this table to confirm a token exists before referencing it. Primitives (`--klp-color-*`) are internal — never reference them from a component.')
  lines.push('')

  if (collisions.size > 0) {
    lines.push('> **Known collisions** — Tailwind v4 compiles more than one theme namespace to the same class prefix (e.g. `--font-*` and `--font-weight-*` both produce `font-` utilities). When two CSS variables below claim the same utility string, only one meaning actually applies at runtime; the other is a false entry kept here for visibility. Do not rely on the font-weight variant through these utilities.')
    lines.push('>')
    for (const [u, owners] of [...collisions].sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(`> - \`${u}\` ← ${[...owners].sort().join(' vs ')}`)
    }
    lines.push('')
  }

  const byGroup = new Map<string, typeof rows>()
  for (const r of rows) {
    if (!byGroup.has(r.group)) byGroup.set(r.group, [])
    byGroup.get(r.group)!.push(r)
  }
  for (const [group, list] of byGroup) {
    lines.push(`## ${group}`)
    lines.push('')
    lines.push('| Figma variable | CSS variable | Tailwind utility |')
    lines.push('|---|---|---|')
    for (const r of list.sort((a, b) => a.cssVar.localeCompare(b.cssVar))) {
      const utilCells = r.utils.map((u) => (collisions.has(u) ? `\`${u}\` ⚠️ collides` : `\`${u}\``))
      lines.push(`| \`${r.figma}\` | \`${r.cssVar}\` | ${utilCells.join(', ')} |`)
    }
    lines.push('')
  }
  return lines.join('\n')
}

// ────────────────────────────────────────────────────────────────────────────
// Main

function main() {
  const raw = readFileSync(tokensJson, 'utf8')
  const tokens = JSON.parse(raw) as TokensFile

  const primitivesCss = buildPrimitives(tokens)
  const aliasesCss    = buildAliases(tokens)
  const themeCss      = buildTheme(tokens)

  writeFileSync(resolve(outDir, 'primitives.css'), primitivesCss)
  writeFileSync(resolve(outDir, 'aliases.css'),    aliasesCss)
  writeFileSync(resolve(outDir, 'theme.css'),      themeCss)

  const docsDir = resolve(process.cwd(), 'docs/tokens')
  writeFileSync(resolve(docsDir, 'vocabulary.md'), buildVocabulary(themeCss))

  const counts = {
    primitives:
      Object.keys(tokens.primitives.colors).length +
      Object.keys(tokens.primitives.spacings).length +
      Object.keys(tokens.primitives.radii).length,
    aliasColors:  Object.keys(tokens.aliasColors).length,
    aliasSpacing: Object.keys(tokens.aliasSpacing).length,
    aliasFont:    Object.keys(tokens.aliasFont).length,
  }

  console.log('✓ sync-tokens complete')
  console.log(`  source    : ${tokens.fileName} (captured ${tokens.capturedAt})`)
  console.log(`  brands    : ${tokens.brands.join(', ')} (default=${tokens.defaultBrand})`)
  console.log(`  primitives: ${counts.primitives}`)
  console.log(`  aliases   : ${counts.aliasColors} colors, ${counts.aliasSpacing} spacing, ${counts.aliasFont} font`)
  console.log(`  output    : src/styles/tokens/{primitives,aliases,theme}.css`)
}

main()
